### ISSUE TITLE
Update to Gnome 45

### ISSUE THREAD

**Issue by soumyaDghosh** [ubuntu/gnome-sdk#170]
Gnome 45 is released, and many apps are gonna push libadwaita 1.4. Can the update be done ASAP?

**Comment by kenvandine** [comment]
@sergio-costas let's take a look at updating libadwaita to 1.4.x

**Comment by 3v1n0** [comment]
As we were discussing with Sergio, I think it would be saner to have a gnome-45-22.04 sdk more than updating the `gnome` generic one, as it may lead to confusion when targetting a specific version.

If possible, the `gnome` one should always refer to the latest version, but we should provide versioned ones if one targets a specific version, so that there's no risk of API/ABI changes.

**Comment by sergio-costas** [comment]
I'm already on it. In fact, it requires recompiling libappstream because there is a change in the API, and I'm not sure if that could result in compatibility problems.

**Comment by seb128** [comment]
Unsure why that was closed? It seems a valid request and not addressed yet?

**Comment by soumyaDghosh** [comment]
@kenvandine @sergio-costas kindly push this to the stable. @sergio-costas Thanks for this PR.

**Comment by soumyaDghosh** [comment]
@kenvandine @sergio-costas kindly push gnome-42-2204 to stable.
